Repository metastable-labs/liquid-interface, pull requests merged in 2024-12, with the labels that each got.

#99 Feature/eng-47/Profile Screen
  app/(tabs)/profile/_layout.tsx
  app/(tabs)/profile/edit-profile.tsx
  assets/icons/edit-profile-icon.tsx
  assets/icons/farcaster-icon.tsx
  assets/icons/fill-check-icon.tsx
  assets/icons/index.ts
  assets/icons/link-icon.tsx
  assets/icons/user-octagon-icon.tsx
  assets/icons/x-ixon.tsx
  components/feed-card/index.tsx
  components/flatlist/index.tsx
  components/image/index.tsx
  components/image/types.ts
  components/index.ts
  hooks/useCustomTabview.tsx
  screens/home/index.tsx
  screens/index.ts
  screens/profile/edit-profile.tsx/index.tsx
  screens/profile/index.tsx
Labels: enhancement, Frontend, UI

#94 Feature/Eng-36/Implement Tanstack
  components/action-card/index.tsx
  components/action-card/types.ts
  components/bottom-sheet/index.tsx
  components/feed-card/feed-step.tsx
  components/feed-card/index.tsx
  components/feed-card/types.ts
  components/pool-images/token-image.tsx
  components/pool-images/types.ts
  components/protocol-card/index.tsx
  components/protocol-card/types.ts
  constants/abis/LiquidStrategy.ts
  constants/abis/SmartWallet.ts
  constants/abis/index.ts
  constants/addresses.ts
  constants/icons.tsx
  hooks/useCalls.ts
  hooks/useLiquid.ts
  init/axios.ts
  init/useViem.ts
  package.json
  providers/AllProviders.tsx
  providers/TanstackProvider.tsx
  providers/index.ts
  screens/create-strategy/actions.tsx
  screens/create-strategy/index.tsx
  screens/create-strategy/new-action-strategy.tsx
  screens/create-strategy/preview-strategy.tsx
  screens/create-strategy/types.ts
  screens/discover/dummy.ts
  screens/discover/index.tsx
  screens/home/dummy.ts
  screens/home/index.tsx
  screens/portfolio/index.tsx
  screens/profile/index.tsx
  services/feeds/apis.ts
  services/feeds/queries.ts
  services/feeds/types.ts
  services/user/apis.ts
  services/user/queries.ts
  services/user/types.ts
  store/app/actions.ts
  store/app/index.ts
  store/app/types.ts
  store/smartAccount/actions.ts
  utils/base64.ts
  utils/encoders.ts
  utils/helpers.ts
  utils/signature.ts
  utils/types.ts
  utils/wallet.ts
  yarn.lock
Labels: enhancement, Frontend

#109 docs: Clarified the Dependency Installation Command in Step 2
  README.md
Labels: documentation
